### ISSUE TITLE
License

### ISSUE THREAD

**Issue by jamesgeddes** [omerkarabacak/bulk-find-and-replace-in-git-repositories#5]
Hi there,

May I request a license on this please?

Thanks!

**Comment by omerkarabacak** [comment]
Hi @jamesgeddes 
I think you already created a PR for MIT but I think it is better to go with GPLv3
What do you think?
Thank you!

**Comment by jamesgeddes** [comment]
Up to you 😊 I will update the PR

**Comment by omerkarabacak** [comment]
Hi @jamesgeddes 

are you going to update the PR?
or I can add it.

Thanks!

**Comment by jamesgeddes** [comment]
@omerkarabacak Apologies for the delay. I have updated the file to include GPLv3.

**Comment by omerkarabacak** [comment]
Thanks!
Merged it.
